name: Hello World
author: Vaishali
description: 'Greet someone and record the time'
inputs:
  who_to_greet:
     description: 'who to greet'
     required: true
     default: 'world'
outputs:
  time:
    description: 'the time we greeted you'
runs:
    using: 'node16'
    main: "dist/index.js"
    pre: "setup.js"
    pre-if: runner.os == 'linux'
    post: "cleanup.js"
    post-if: runner.os == 'linux'