name: Stale Issues & PRs
on:
  schedule:
    # - cron: "0 17 * * *"
    # - cron: "0/5 * * * *" # JUST FOR TESTING
    # uncomment above two lines to run the workflow on a schedule

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: "This is some message."
          days-before-stale: 1
          days-before-close: 5