name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "Alisha"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: cvaishu6/workflows/.github/workflows/reusable.yaml@master
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}