name: workflow commands
on: [push]
jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error message
        run: echo "::error title=Error title, file=app.js,line=2,endLine=3,col=5,endCol=7::Missing semicolon"
      - name: Setting warning message
        run: echo "::warning title=Warning title, file=app.js,line=2,endLine=3,col=5,endCol=7::Missing semicolon"
      - name: Setting debug message
        run: echo "::debug title=Debug title, file=app.js,line=2,endLine=3,col=5,endCol=7::Missing semicolon"
      - name: Setting an notice message
        run: echo "::notice title=Notice title, file=app.js,line=2,endLine=3,col=5,endCol=7::Missing semicolon"