name: workflow commands
on: [push]
jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error message
        run: echo "::error title=Error title, file=app.js,line=2,endLine=3,col=5,endCol=7::Missing semicolon"
      - name: Setting warning message
        run: echo "::warning title=Warning title, file=app.js,line=2,endLine=3,col=5,endCol=7::Missing semicolon"
      - name: Setting debug message
        run: echo "::debug title=Debug title, file=app.js,line=2,endLine=3,col=5,endCol=7::Missing semicolon"
      - name: Setting an notice message
        run: echo "::notice title=Notice title, file=app.js,line=2,endLine=3,col=5,endCol=7::Missing semicolon"
      - name: Group of logs
        run: |
          echo "::group::My Group Name"
          echo "content of the group"
          echo "::endgroup::"
      - name: masking a value
        run: echo "::add-mask::secret string"
      - name: echo a secret
        run: echo "secret string"        